author: Jérémie C Wenger
title: Recursus 
email: jeremie[dot]wenger[at]gmail[dot]com
website: jeremiewenger.com
description: >-
  Thoughts, resources and research around my final project for the <a href="https://www.gold.ac.uk/pg/ma-computational-arts/">MA in Computational Arts</a>, Goldsmiths College, London.
baseurl: ""
url: "http://recursus.co"
github_username: jchwenger 

# Build settings
markdown: kramdown
theme: minima
plugins:  
- jekyll-feed
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
